[package]
name = "Werilog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parser_rust_simple = { git = "https://github.com/yportne13/parser_rust_simple" }
